### ISSUE TITLE
第六课的内容会被defender杀。

### ISSUE THREAD

**Issue by Rail1gun** [Rvn0xsy/BadCode#2]
你好，大佬，第六课的代码我在10月16日尝试时发现，会被defender杀掉，原因我认为是msf生成的DLL没有经过免杀处理，如果只是在虚拟机中搭建msf，生成的马在VT上检测时，因请求不到DLL，所以不会报毒，而在vps上搭建msf，VT能请求到DLL后，就会报毒。所以，应该需要单独对DLL也进行免杀处理才行。最后请问一下，第六课的上线方法，能使用CS中的DLL上线吗？

**Comment by Rvn0xsy** [comment]
可以的，只不过DLL如果还做免杀，工作量有点大，还是要专注于加载器的编写。

你可以尝试新版：https://github.com/Rvn0xsy/Cooolis-ms 代码获得灵感。

**Comment by byioi** [comment]
大佬你好，我在msf的发射器里填cs的dll，发现加载后会崩溃，是哪一步出错了吗？
