### ISSUE TITLE
BadCodeUUID 代码报错

### ISSUE THREAD

**Issue by SnowMeteors** [Rvn0xsy/BadCode#5]
复制粘贴使用vs编译第40行报错
``` 
RPC_STATUS	status = UuidFromStringA(RPC_CSTR(buf[i]), (UUID*)CodePtr);
```
改为下面代码通过
```
RPC_STATUS	status = UuidFromStringA((RPC_CSTR)buf[i], (UUID*)CodePtr);
```

**Comment by Rvn0xsy** [comment]
> 复制粘贴使用vs编译第40行报错
> 
> ```
> RPC_STATUS	status = UuidFromStringA(RPC_CSTR(buf[i]), (UUID*)CodePtr);
> ```
> 
> 改为下面代码通过
> 
> ```
> RPC_STATUS	status = UuidFromStringA((RPC_CSTR)buf[i], (UUID*)CodePtr);
> ```

感谢提醒，已经修复！
